### ISSUE TITLE
Add InputHTMLAttributes into Button

### ISSUE THREAD

**Issue by raczyk** [nordcloud/GNUI#181]
**What problem does this feature solve?**

There is a lack of HTML attributes in Button types src/components/button/Button.tsx

**What is expected?**

The button should accept all HTML attributes and all existing custom props.

**Comment by nowyDEV** [comment]
resolved in https://github.com/nordcloud/GNUI/commit/d0a827c16c94d0280810e67c86b3c5ca9ffe60ee
