### ISSUE TITLE
The accordion has the wrong story implementation

### ISSUE THREAD

**Issue by janosio-nordcloud** [nordcloud/GNUI#185]
### What problem does this feature solve?
The expanded accordion has the wrong story implementation

<img width="990" alt="Zrzut ekranu 2020-10-8 o 08 56 27" src="https://user-images.githubusercontent.com/58164749/95425823-2bf80500-0945-11eb-9efb-d14bab83638d.png">

### What is expected?
- Only one element inside the accordion

**Comment by GaganSingh5** [comment]
Hi dev @janosio-nordcloud  I would like to work on this Issue.

**Comment by janosio-nordcloud** [comment]
@GaganSingh5 go ahead.
