### ISSUE TITLE
Make components out of icon paths

### ISSUE THREAD

**Issue by nowyDEV** [nordcloud/GNUI#196]
File src/utils/svgicons.tsx

contains React jsx icon paths, the paths should be moved to the IconPaths folder inside components/, then imported and returned inside svgicons.tsx file.

**Comment by fasemoreakinyemi** [comment]
please assign this issue if it's still opened

**Comment by fasemoreakinyemi** [comment]
please assign this issue to me if it's still opened

**Comment by nowyDEV** [comment]
> please assign this issue to me if it's still opened

Done
