### ISSUE TITLE
Remove unused files/folders

### ISSUE THREAD

**Issue by nowyDEV** [nordcloud/GNUI#197]
Remove:

src/utils/wInfo.ts
src/utils/img

**Comment by fasemoreakinyemi** [comment]
There's no contribution directives in your repo

**Comment by nowyDEV** [comment]
> There's no contribution directives in your repo

We will add them asap

**Comment by shalika10** [comment]
@nowyDEV i can sign-up for same ,please assign it to me

**Comment by nowyDEV** [comment]
Resolved in #200 #199
