### ISSUE TITLE
Pass props into native elements

### ISSUE THREAD

**Issue by nowyDEV** [nordcloud/GNUI#201]
Some components take only a few props that are required for logic inside their code, they should spread all of the remaining props that was passed into them to the native html element, you should also remove redundant native attributes/event handlers from props type interface and extend it with the one provided by React.

You can see how it should be done inside 
src/components/checkbox/Checkbox.tsx
src/components/switch/Switch.tsx

Components to refactor:

- [x] src/components/toggle
- [x] src/components/text (fix types)
- [x] src/components/svgicon (fix types)
- [x] src/components/selectbutton (fix types)
- [x] src/components/message/Message.tsx (fix types)

**Comment by MykolaKolotylo** [comment]
hey @nowyDEV can I try to do it?

**Comment by nowyDEV** [comment]
> hey @nowyDEV can I try to do it?

Sure, go ahead

**Comment by MykolaKolotylo** [comment]
hi @nowyDEV, sent a PR, please review https://github.com/nordcloud/GNUI/pull/224
