### ISSUE TITLE
Reorganize stories

### ISSUE THREAD

**Issue by nowyDEV** [nordcloud/GNUI#210]
Right now, all of the `*.stories.mdx` files reside inside src/stories folder,
please move every story to its component folder.

**Comment by Jeremy-Walton** [comment]
I would like to try this. Can you assign me?

**Comment by nowyDEV** [comment]
> I would like to try this. Can you assign me?

Sure, go ahead

**Comment by Jeremy-Walton** [comment]
@nowyDEV made https://github.com/nordcloud/GNUI/pull/213 to address this.
