### ISSUE TITLE
Add useDisclosure hook for boolean states

### ISSUE THREAD

**Issue by nowyDEV** [nordcloud/GNUI#498]
There's a handy hook that we use in our internal projects that is used to handle boolean states.

```tsx
import { useCallback, useState } from "react";

export function useDisclosure(isOpenDefault = false) {
  const [isOpen, setIsOpen] = useState(isOpenDefault);

  const open = useCallback(() => setIsOpen(true), []);
  const close = useCallback(() => setIsOpen(false), []);

  const toggle = useCallback((toSet?: boolean) => {
    if (typeof toSet === "undefined") {
      setIsOpen((state) => !state);
    } else {
      setIsOpen(toSet);
    }
  }, []);

  return { isOpen, open, close, toggle };
}
```

Tasks:
- Add above hook to `src/hooks`
- Refactor usages of boolean states inside the codebase to `useDisclosure`
- To find code that requires refactor, make use of global search and search for `useState(false)` or `useState(true)`

**Comment by TDP17** [comment]
Hi, I'd like to take a stab at this. Before starting I had a few questions

**Which one of the two is preferable here?**
```
const { isOpen, open, close, toggle: setOpen } = useDisclosure(false);
close();
```
```
const disclosureHook = useDisclosure(false);
disclosureHook.toggle();
```

**Which one of the two is preferable here? (I assume close since it doesn't add an extra type check)**
In case of a setState(false) -> If I have understood it correctly, `toggle(false)` and `close()` will do essentially the same thing.

**Comment by nowyDEV** [comment]
> Hi, I'd like to take a stab at this. Before starting I had a few questions
> 
> **Which one of the two is preferable here?**
> 
> ```
> const { isOpen, open, close, toggle: setOpen } = useDisclosure(false);
> close();
> ```
> 
> ```
> const disclosureHook = useDisclosure(false);
> disclosureHook.toggle();
> ```
> 
> **Which one of the two is preferable here? (I assume close since it doesn't add an extra type check)** In case of a setState(false) -> If I have understood it correctly, `toggle(false)` and `close()` will do essentially the same thing.

Below version is preferable (use `toggle` only if necessary, prefer close/open).

```tsx
const { isOpen, close, open, toggle } = useDisclosure();
```
